routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PendudukController;
use App\Http\Controllers\DisposisiController;
use App\Http\Controllers\CetakSuratController;
use App\Http\Controllers\JenisSuratController;
use App\Http\Controllers\SuratMasukController;
use App\Http\Controllers\SuratKeluarController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {

    // Data Json 
Route::get('/penduduk/datajson', [PendudukController::class, 'dataJson'])->name('penduduk.json');
Route::get('/jenis_surat/datajson', [JenisSuratController::class, 'dataJson'])->name('jenis_surat.json');
Route::get('/surat_masuk/datajson', [SuratMasukController::class, 'dataJson'])->name('surat_masuk.json');
Route::get('/surat_keluar/datajson', [SuratKeluarController::class, 'dataJson'])->name('surat_keluar.json');
Route::get('/cetak/surat/datajson', [CetakSuratController::class, 'dataJson'])->name('cetak_surat.json');
Route::get('/disposisi/datajson', [DisposisiController::class, 'dataJson'])->name('disposisi.json');

Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
Route::get('/surat_masuk', [CetakSuratController::class, 'index'])->name('surat');
Route::post('/surat_masuk', [CetakSuratController::class, 'store'])->name('surat.store');
Route::delete('/surat_masuk/{id}', [CetakSuratController::class, 'destroy'])->name('surat.destroy');
Route::get('/cetak_surat', [CetakSuratController::class, 'index'])->name('cetak_surat');
Route::get('/disposisi', [DisposisiController::class, 'index'])->name('disposisi');
Route::get('/disposisi/acc/{id}', [DisposisiController::class, 'acc_disposisi'])->name('acc.disposisi');
Route::get('/surat_keluar/acc/{id}', [SuratKeluarController::class, 'acc_surat_keluar'])->name('acc.surat_keluar');
Route::get('/surat_keluar/tolak/{id}', [SuratKeluarController::class, 'tolak_surat_keluar'])->name('tolak.surat_keluar');

    // PDF
Route::get('/foto_surat_masuk/pdf/{id}', [CetakSuratController::class, 'foto_surat_masuk'])->name('foto_surat_masuk');
Route::get('/skck/pdf/{id}', [CetakSuratController::class, 'pdf_skck'])->name('pdf_skck');
Route::get('/pindah_rumah/pdf/{id}', [CetakSuratController::class, 'pdf_pindah_rumah'])->name('pdf_pindah');
Route::get('/blm_pny_rmh/pdf/{id}', [CetakSuratController::class, 'pdf_blm_pny_rmh'])->name('pdf_blm_pny');
Route::get('/nikah_satu/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_satu'])->name('pdf_nikah_satu');
Route::get('/nikah_empat/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_empat'])->name('pdf_nikah_empat');
Route::get('/nikah_lima/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_lima'])->name('pdf_nikah_lima');
Route::get('/disposisi/pdf/{id}', [CetakSuratController::class, 'cetak_disposisi'])->name('pdf_disposisi');

Route::get('/report/surat_masuk', [CetakSuratController::class, 'surat_masuk'])->name('report.surat_masuk');
Route::get('/report/surat_Keluar', [CetakSuratController::class, 'surat_keluar'])->name('report.surat_keluar');
Route::get('/report/disposisi', [CetakSuratController::class, 'disposisi'])->name('report.disposisi');
Route::get('/cetak_report/surat_masuk', [CetakSuratController::class, 'report_surat_masuk'])->name('cetak_report.surat_masuk');

Route::get('/report/pdf_surat_masuk', [CetakSuratController::class, 'pdf_surat_masuk'])->name('report.pdf_surat_masuk');
Route::get('/report/pdf_surat_keluar', [CetakSuratController::class, 'pdf_surat_keluar'])->name('report.pdf_surat_keluar');
Route::get('/report/pdf_disposisi', [CetakSuratController::class, 'pdf_disposisi'])->name('report.pdf_disposisi');

Route::resource('penduduk', PendudukController::class);
Route::resource('jenis_surat', JenisSuratController::class);
Route::resource('surat_masuk', SuratMasukController::class);
Route::resource('surat_keluar', SuratKeluarController::class);
Route::resource('manajemen_user', UserController::class);

// Manajemen User
// Route::get('/manajemen_user', [UserController::class, 'index'])->name('manajemen_user.index');
// Route::post('/manajemen_user', [UserController::class, 'store'])->name('manajemen_user.store');
// Route::get('/manajemen_user/{manajemen_user}/edit', [UserController::class, 'edit'])->name('edit');
// Route::patch('/manajemen_user/update/{manajemen_user}', [UserController::class, 'update'])->name('update');
// Route::get('/manajemen_user/show/{manajemen_user}', [UserController::class, 'show'])->name('show');

});

resources/views/manajemen_user/edit.blade.php
 <div class="row">
     <div class="col-md-6">
         <div class="form-group">
             <input type="hidden" value="{{ $user->id }}" id="id_data" />
             <label>Nama User</label> <b><span class="text-danger" id="nameError"></span></b>
             <input id="name" name="name" placeholder="Masukkan Nama User" type="text" class="form-control"
                 value="{{$user->name}}">
         </div>
     </div>
     <div class="col-md-6">
         <div class="form-group">
             <label>Role Akses</label> 
             <select id="dinamik" name="role" class="form-control border-primary">
                <option value="{{$user->role}}" selected>{{$user->role}}</option>
                <option value="admin">Admin</option>
            </select>
            <br>
         </div>
     </div>
     <div class="col-md-6">
        <div class="form-group">
     <label>Tambah Role Akses</label>
        <div class="input-group mb-5">
      <input class="form-control" type="text" id="add_valu" name="role" placeholder="Masukkan Role Akses">
      <br>
      <div class="input-group-append">
        <button class="btn btn-warning btn-sm" type="button" id="btn_add_val">Tambah Role</button>
    </div>
    </div>
        </div>
    </div>
     <div class="col-md-6">
         <div class="form-group">
             <label>Email</label> <b><span class="text-danger" id="emailError"></span></b>
             <input id="email" name="email" placeholder="Masukkan Email" type="email" class="form-control"
                 value="{{$user->email}}">
         </div>
     </div>
     <div class="col-md-12">
         <div class="form-group">
             <label>Password</label> <b><span class="text-danger" id="passwordError"></span></b>
             <input id="password" name="password" placeholder="Masukkan Password" type="password" class="form-control"
                 value="">
         </div>
     </div>

resources/views/manajemen_user/index.blade.php
@extends ('layouts.base')
@section('title', 'Data User')
@section('content')
<div class="content">
</div>

<div class="page-header">
  <ul class="breadcrumbs">
      <li class="nav-home">
          <a href="#">
              <i class="flaticon-home"></i>
          </a>
      </li>
      <li class="separator">
          <i class="flaticon-right-arrow"></i>
      </li>
      <li class="nav-item">
          <a href="#">Data User</a>
      </li>
  </ul>
</div>

    <section class="content" style="padding-top: 5px">
      <div style="margin-bottom: 10px;" class="row">
    <div class="col-lg-12">
          
            @if (session('status'))
                <div class="">
                    {{ session('status') }}
                </div>
            @endif
    </div>
      </div>

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <div class="d-flex align-items-center">
            <h4 class="card-title">Data User</h4>
            <button class="btn btn-primary btn-round btn-sm ml-auto" data-toggle="modal" data-target="#exampleModal">Tambah Data User</button>
          </div>
        </div>
          

        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped custom-table w-100" id="table-1">
              <thead>                                 
                <tr>
                  <th>#</th>
                  <th>Nama</th>
                  <th>Role Akses</th>
                  <th>Email</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody>             
                @foreach ($user as $item)
                <tr>
                  <td>{{ $no++ }}</td>
                  <td>{{ $item->name ?? null}}</td>
                  <td>{{ $item->role ?? null}}</td>
                  <td>{{ $item->email ?? null}}</td>
                  <td width="100" class="text-center">
                  
                  <a href="#" data-id="{{$item->id}}" class="btn btn-link btn-edit btn-info shadow btn-sm"><i class="far fa-edit"></i></a>
                  <a href="#" data-id="{{$item->id}}" class="btn btn-link btn-detail btn-danger shadow btn-sm swal-6 "><i class="fas fa-trash"></i></a>
                  <form action="{{ route('manajemen_user.destroy', $item->id) }}" id="delete{{ $item->id }}" method="post" style="display: inline-block;">
                     @method('delete')
                     @csrf        
                    </form>
                    </td>
                  </tr>
                @endforeach                    
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
    </section>
  @section('modal')

  {{-- MODAL TAMBAH DATA --}}
  <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Tambah Data User</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form action="{{ route('manajemen_user.store') }}" method="POST">
                @csrf
              <div class="modal-body">
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label @error('name') class="text-danger" @enderror>Nama User @error('name') | {{ $message }} @enderror</label>
                      <input id="name" name="name" placeholder="Masukkan Nama" type="text" class="form-control" value="{{old('name')}}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label @error('role') class="text-danger" @enderror>Role Akses @error('role') | {{ $message }} @enderror</label>
                      <select id="dynamic" name="role" class="form-control border-primary">
                        <option value="{{old('role')}}">-- Pilih Role --</option>
                        <option value="admin">Admin</option>
                    </select>
                    <br>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                 <label>Tambah Role Akses</label>
                    <div class="input-group mb-3">
                  <input class="form-control" type="text" id="add_val" name="role" placeholder="Masukkan Role Akses">
                  <br>
                  <div class="input-group-append">
                    <button class="btn btn-warning btn-sm" type="button" id="bt_add_val">Tambah Role</button>
                </div>
                </div>
                    </div>
                </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label @error('email') class="text-danger" @enderror>Email @error('email') | {{ $message }} @enderror</label>
                      <input id="email" name="email" placeholder="Masukkan Email" type="email" class="form-control" value="{{old('email')}}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label @error('password') class="text-danger" @enderror>Password @error('password') | {{ $message }} @enderror</label>
                      <input id="password" name="password" placeholder="Masukkan Password" type="password" class="form-control" value="{{old('password')}}">
                    </div>
                  </div>
            </div>
          </div>
              <div class="modal-footer bg-whitesmoke br">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>

              </div>
            </form>
          </div>
      </div>
  </div>

  {{-- MODAL LIHAT DATA --}}
  <div class="modal fade" tabindex="-1" role="dialog" id="modal-lihat">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Lihat Data User</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form action="{{ route('manajemen_user.store') }}" method="POST" id="form-show">
                @csrf
              <div class="modal-body">
                
              </div>
              <div class="modal-footer bg-whitesmoke br">
                  <button type="button" class="btn btn-dark" data-dismiss="modal">Tutup</button>
                  {{-- <button type="submit" class="btn btn-primary">Simpan</button> --}}
              </div>
            </form>
          </div>
      </div>
  </div>

  {{-- MODAL EDIT DATA --}}
  <div class="modal fade" tabindex="-1" role="dialog" id="modal-edit">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Edit Data User</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form action="{{ route('manajemen_user.store') }}" method="POST" id="form-edit">
              {{-- @method('patch') --}}
                @csrf
              <div class="modal-body">

              </div>
              <div class="modal-footer bg-whitesmoke br">
                <button type="button" class="btn btn-primary btn-update">Simpan</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
              </div>
            </form>
          </div>
      </div>
  </div>

  @endsection

@endsection
@push ('page-scripts')
@include('manajemen_user.js.user-js')
@endpush

resources/views/manajemen_user/kopit.blade.php
@extends ('layouts.master')
@section('title', 'Your App Name')
@section('content')
<div class="content">
</div>

<div class="section-header">
    <h1>Barang</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
      <div class="breadcrumb-item">Barang</div>
    </div>
  </div>

    <section class="content" style="padding-top: 5px">
      <div style="margin-bottom: 10px;" class="row">
    <div class="col-lg-12">
          <button class="btn btn-icon icon-left btn-primary" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus"></i>Tambah Data</button>
            @if (session('status'))
                <div class="">
                    {{ session('status') }}
                </div>
            @endif
    </div>
      </div>

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4>Note</h4>
        </div>

        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-hover table-striped" id="table-1">
              <thead>                                 
                <tr class="table-info">
                  <th>#</th>
                  <th>Provinsi</th>
                  <th>Positif</th>
                  <th>Sembuh</th>
                  <th>Meninggal</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody>             
                @foreach ($data as $item)
                <tr>
                  <td>{{ $no++ }}</td>
                  <td>{{ $item['attributes']['Provinsi']}}</td>
                  <td>{{ $item['attributes']['Kasus_Posi']}}</td>
                  <td>{{ $item['attributes']['Kasus_Semb']}}</td>
                  <td>{{ $item['attributes']['Kasus_Meni']}}</td>
                  {{-- <td>
                  <a href="#" data-id="{{$item->id}}" class="btn btn-icon btn-success btn-sm btn-show"><i class="far fa-eye"></i></a>
                  <a href="#" data-id="{{$item->id}}" class="btn btn-icon btn-primary btn-sm btn-edit"><i class="far fa-edit"></i></a>
                  <a href="#" data-id="{{$item->id}}" class="btn btn-icon btn-danger btn-sm swal-6 "><i class="fas fa-trash"></i></a>
                  <form action="{{ route('barang.delete', $item->id) }}" id="delete{{ $item->id }}" method="post" style="display: inline-block;">
                     @method('delete')
                     @csrf        
                    </form>
                    </td> --}}
                  </tr>
                @endforeach                    
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
    </section>
  @section('modal')

  {{-- MODAL TAMBAH DATA --}}
  <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Tambah Note</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form action="{{ route('store') }}" method="POST">
                @csrf
              <div class="modal-body">
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label @error('title') class="text-danger" @enderror>Title @error('title') | {{ $message }} @enderror</label>
                      <input id="title" name="title" placeholder="Masukkan Title" type="text" class="form-control" value="{{old('title')}}">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label @error('description') class="text-danger" @enderror>Deskripsi @error('description') | {{ $message }} @enderror</label>
                      <input id="description" name="description" placeholder="Masukkan Deskripsi" type="text" class="form-control" value="{{old('description')}}">
                    </div>
                  </div>
            </div>
          </div>
              <div class="modal-footer bg-whitesmoke br">
                  <button type="button" class="btn btn-dark" data-dismiss="modal">Tutup</button>
                  <button type="submit" class="btn btn-primary">Simpan</button>
              </div>
            </form>
          </div>
      </div>
  </div>

  {{-- MODAL LIHAT DATA --}}
  <div class="modal fade" tabindex="-1" role="dialog" id="modal-lihat">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Lihat Note</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form action="{{ route('store') }}" method="POST" id="form-show">
                @csrf
              <div class="modal-body">
                
              </div>
              <div class="modal-footer bg-whitesmoke br">
                  <button type="button" class="btn btn-dark" data-dismiss="modal">Tutup</button>
                  {{-- <button type="submit" class="btn btn-primary">Simpan</button> --}}
              </div>
            </form>
          </div>
      </div>
  </div>

  {{-- MODAL EDIT DATA --}}
  <div class="modal fade" tabindex="-1" role="dialog" id="modal-edit">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Edit Note</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <form action="{{ route('store') }}" method="POST" id="form-edit">
              {{-- @method('patch') --}}
                @csrf
              <div class="modal-body">

              </div>
              <div class="modal-footer bg-whitesmoke br">
                  <button type="button" class="btn btn-dark" data-dismiss="modal">Tutup</button>
                  <button type="button" class="btn btn-primary btn-update">Simpan</button>
              </div>
            </form>
          </div>
      </div>
  </div>
  @endsection

@endsection
@push ('page-scripts')


<script>
  @if($errors->any())
      $('#exampleModal').modal('show')
  @endif

  $(".swal-6").click(function(e) {
    id = e.target.dataset.id;
  swal({
      title: 'Kamu Yakin Mau Hapus?',
      text: 'Jika di Hapus, Data akan hilang!',
      icon: 'warning',
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
      swal('Data Berhasil di  Hapus :)', {
        icon: 'success',
      });
      $(`#delete${id}`).submit();
      } else {
      swal('Your imaginary file is safe!');
      }
    });
});

      $('.btn-edit').on('click', function() {
        let id = $(this).data('id')
        $.ajax({
          url:`/barang/${id}/edit`,
          method:"GET",
          success: function(data) {
            $('#modal-edit').find('.modal-body').html(data)
            $('#modal-edit').modal('show')
          },
          error:function(error){
            console.log(error)
          }
        })
      })

      $('.btn-update').on('click', function() {
        let id = $('#form-edit').find('#id_data').val()
        let formData = $('#form-edit').serialize()
        $.ajax({
          url:`/barang/update/${id}`,
          method:"PATCH",
          data:formData,
          success: function(data) {
            // $('#modal-edit').find('.modal-body').html(data)
            $('#modal-edit').modal('hide')
            window.location.assign('/barang')
          },
          error:function(err){
            console.log(err)
          }
        })
      })

      $('.btn-show').on('click', function() {
        let id = $(this).data('id')
        $.ajax({
          url:`/barang/show/${id}`,
          method:"GET",
          success: function(data) {
            $('#modal-lihat').find('.modal-body').html(data)
            $('#modal-lihat').modal('show')
          },
          error:function(error){
            console.log(error)
          }
        })
      })
</script>
@endpush

resources/views/manajemen_user/show.blade.php
<div class="row">
    <div class="card-body">
        <ul class="list-group">
          <li class="list-group-item">
            <h6 class="mb-0 mt-1">Hak Cuti</h6>
            <p class="mb-0">{{ $karyawan->hak_cuti }} Hari</p>
          </li>
          <li class="list-group-item">
            <h6 class="mb-0 mt-1">NIP</h6>
            <p class="mb-0">{{ $karyawan->nip }}</p>
          </li>
          <li class="list-group-item">
            <h6 class="mb-0 mt-1">Nama</h6>
            <p class="mb-0">{{ $karyawan->nama }}</p>
          </li>
          <li class="list-group-item">
            <h6 class="mb-0 mt-1">Dept</h6>
            <p class="mb-0">{{ $karyawan->dept }}</p>
          </li>
          
        </ul>
    </div>
        <div class="row">
          <div class="card-body">
        <ul class="list-group">
          <li class="list-group-item">
            <h6 class="mb-0 mt-1">Grade</h6>
            <p class="mb-0">{{ $karyawan->grade }}</p>
          </li>
          <li class="list-group-item">
            <h6 class="mb-0 mt-1">Job</h6>
            <p class="mb-0">{{ $karyawan->job }}</p>
          </li>
          <li class="list-group-item">
            <h6 class="mb-0 mt-1">Nomor Telepon</h6>
            <p class="mb-0">{{ $karyawan->no_telp }}</p>
          </li>
      </ul>
      </div>