routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PendudukController;
use App\Http\Controllers\DisposisiController;
use App\Http\Controllers\CetakSuratController;
use App\Http\Controllers\JenisSuratController;
use App\Http\Controllers\SuratMasukController;
use App\Http\Controllers\SuratKeluarController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {

    // Data Json 
Route::get('/penduduk/datajson', [PendudukController::class, 'dataJson'])->name('penduduk.json');
Route::get('/jenis_surat/datajson', [JenisSuratController::class, 'dataJson'])->name('jenis_surat.json');
Route::get('/surat_masuk/datajson', [SuratMasukController::class, 'dataJson'])->name('surat_masuk.json');
Route::get('/surat_keluar/datajson', [SuratKeluarController::class, 'dataJson'])->name('surat_keluar.json');
Route::get('/cetak/surat/datajson', [CetakSuratController::class, 'dataJson'])->name('cetak_surat.json');
Route::get('/disposisi/datajson', [DisposisiController::class, 'dataJson'])->name('disposisi.json');

Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
Route::get('/surat_masuk', [CetakSuratController::class, 'index'])->name('surat');
Route::post('/surat_masuk', [CetakSuratController::class, 'store'])->name('surat.store');
Route::delete('/surat_masuk/{id}', [CetakSuratController::class, 'destroy'])->name('surat.destroy');
Route::get('/cetak_surat', [CetakSuratController::class, 'index'])->name('cetak_surat');
Route::get('/disposisi', [DisposisiController::class, 'index'])->name('disposisi');
Route::get('/disposisi/acc/{id}', [DisposisiController::class, 'acc_disposisi'])->name('acc.disposisi');
Route::get('/surat_keluar/acc/{id}', [SuratKeluarController::class, 'acc_surat_keluar'])->name('acc.surat_keluar');
Route::get('/surat_keluar/tolak/{id}', [SuratKeluarController::class, 'tolak_surat_keluar'])->name('tolak.surat_keluar');

    // PDF
Route::get('/foto_surat_masuk/pdf/{id}', [CetakSuratController::class, 'foto_surat_masuk'])->name('foto_surat_masuk');
Route::get('/skck/pdf/{id}', [CetakSuratController::class, 'pdf_skck'])->name('pdf_skck');
Route::get('/pindah_rumah/pdf/{id}', [CetakSuratController::class, 'pdf_pindah_rumah'])->name('pdf_pindah');
Route::get('/blm_pny_rmh/pdf/{id}', [CetakSuratController::class, 'pdf_blm_pny_rmh'])->name('pdf_blm_pny');
Route::get('/nikah_satu/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_satu'])->name('pdf_nikah_satu');
Route::get('/nikah_empat/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_empat'])->name('pdf_nikah_empat');
Route::get('/nikah_lima/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_lima'])->name('pdf_nikah_lima');
Route::get('/disposisi/pdf/{id}', [CetakSuratController::class, 'cetak_disposisi'])->name('pdf_disposisi');

Route::get('/report/surat_masuk', [CetakSuratController::class, 'surat_masuk'])->name('report.surat_masuk');
Route::get('/report/surat_Keluar', [CetakSuratController::class, 'surat_keluar'])->name('report.surat_keluar');
Route::get('/report/disposisi', [CetakSuratController::class, 'disposisi'])->name('report.disposisi');
Route::get('/cetak_report/surat_masuk', [CetakSuratController::class, 'report_surat_masuk'])->name('cetak_report.surat_masuk');

Route::get('/report/pdf_surat_masuk', [CetakSuratController::class, 'pdf_surat_masuk'])->name('report.pdf_surat_masuk');
Route::get('/report/pdf_surat_keluar', [CetakSuratController::class, 'pdf_surat_keluar'])->name('report.pdf_surat_keluar');
Route::get('/report/pdf_disposisi', [CetakSuratController::class, 'pdf_disposisi'])->name('report.pdf_disposisi');

Route::resource('penduduk', PendudukController::class);
Route::resource('jenis_surat', JenisSuratController::class);
Route::resource('surat_masuk', SuratMasukController::class);
Route::resource('surat_keluar', SuratKeluarController::class);
Route::resource('manajemen_user', UserController::class);

// Manajemen User
// Route::get('/manajemen_user', [UserController::class, 'index'])->name('manajemen_user.index');
// Route::post('/manajemen_user', [UserController::class, 'store'])->name('manajemen_user.store');
// Route::get('/manajemen_user/{manajemen_user}/edit', [UserController::class, 'edit'])->name('edit');
// Route::patch('/manajemen_user/update/{manajemen_user}', [UserController::class, 'update'])->name('update');
// Route::get('/manajemen_user/show/{manajemen_user}', [UserController::class, 'show'])->name('show');

});

app/Models/JenisSurat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class JenisSurat extends Model
{
    use HasFactory;

    protected $table = 'jenis_surat';
    protected $fillable = [
        'nama_surat',
        'jenis_surat',
    ];

    public function surat_masuk()
    {
        return $this->hasMany(SuratMasuk::class);
    }


}

app/Http/Controllers/JenisSuratController.php
<?php

namespace App\Http\Controllers;

use App\Models\JenisSurat;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class JenisSuratController extends Controller
{
    public function dataJson()
    {
        return DataTables::of(JenisSurat::orderByDesc('id')->get())
            ->addColumn('action', function ($row) {

                $action = '<a href="javascript:void(0);" 
                data-nama_surat="'.$row->nama_surat.'" 
                data-jenis_surat="'.$row->jenis_surat.'"
                class="btn btn-link btn-detail btn-info shadow btn-sm"> 
                <i class="fa fa-eye"></i></a>

                
                <a href="javascript:void(0);" class="btn btn-link btn-primary btn-md btn-edit" data-id="'.$row->id.'" data-nama_surat="'.$row->nama_surat.'" data-jenis_surat="'.$row->jenis_surat.'"><i class="fa fa-edit"></i></a> 
                
                <a href="javascript:void(0);" data-id="'.$row->id.'" class="btn btn-link btn-danger btn-md btn-delete"><i class="fa fa-times"></i></a>';
                return $action;
            })
            ->make(true);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('jenis_surat.index');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama_surat' => 'required',
            'jenis_surat' => 'required',
        ]);

        $req_jenis_surat = $request->all();

        if ($request->id) {

            $jenis_surat = JenisSurat::find($request->id);
            $jenis_surat->update($req_jenis_surat);
            $message = "Data Jenis Surat Berhasil diupdate";


        } else {

            $jenis_surat = JenisSurat::create($req_jenis_surat);
            $message = "Data Jenis Surat Berhasil Disimpan";

        }

        return back()->with('success', $message);
    }

    public function destroy($id)
    {
        $jenis_surat = JenisSurat::find($id);
        $jenis_surat->delete();

        return back();
    }
}

resources/views/jenis_surat/index.blade.php
@extends ('layouts.base')
@section('title', 'Jenis Surat')
@section('content')

  {{-- content start --}}
  <div class="page-header">
    <ul class="breadcrumbs">
        <li class="nav-home">
            <a href="#">
                <i class="flaticon-home"></i>
            </a>
        </li>
        <li class="separator">
            <i class="flaticon-right-arrow"></i>
        </li>
        <li class="nav-item">
            <a href="#">Jenis Surat</a>
        </li>
    </ul>
</div>
  <div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="d-flex align-items-center">
                    <h4 class="card-title">Jenis Surat</h4>
                    <button class="btn btn-primary btn-round btn-sm ml-auto add-btn" data-toggle="modal" data-target="#modal_jenis_surat">
                        <i class="fa fa-plus"></i>
                        Tambah
                    </button>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="table-datatable" class="table table-striped custom-table w-100">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama Surat</th>
                                <th>Jenis Surat</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{{-- content end --}}

{{-- modal start --}}

{{-- Jenis Surat Modal start --}}

<div id="modal_jenis_surat" class="modal custom-modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><span>Tambah</span> Jenis Surat</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ route('jenis_surat.store') }}">
                    @csrf
                    <input type="hidden" id="id" name="id">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-form-label">Nama Surat<span class="text-danger">*</span></label>
                                <input class="form-control" id="nama_surat" name="nama_surat" type="text" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-form-label">Jenis Surat<span class="text-danger">*</span></label>
                                <select name="jenis_surat" class="form-control" id="jenis_surat">
                                    <option value="">- Pilih -</option>
                                    <option value="Surat Masuk">Surat Masuk</option>
                                    <option value="Surat Keluar">Surat Keluar</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer no-bd">
                        <button class="btn btn-primary submit-btn">Simpan</button>
                        <button class="btn btn-danger" data-dismiss="modal">Tutup</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{{-- Jenis Surat Modal end --}}

{{--  Jenis Surat Detail Modal start --}}
<div id="modal_jenis_surat_detail" class="modal custom-modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><span>Detail</span> Jenis Surat</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-striped table-border">
                            <tbody>
                                <tr>
                                    <td>NIK :</td>
                                    <td class="text-right" id="nik"></td>
                                </tr>
                                <tr>
                                    <td>Nama :</td>
                                    <td class="text-right" id="nama"></td>
                                </tr>
                                <tr>
                                    <td>Tempat Lahir :</td>
                                    <td class="text-right" id="tempat_lahir"></td>
                                </tr>
                                <tr>
                                    <td>Tanggal Lahir :</td>
                                    <td class="text-right" id="tgl_lahir"></td>
                                </tr>
                                <tr>
                                    <td>Jenis Kelamin :</td>
                                    <td class="text-right" id="jenis_kelamin"></td>
                                </tr>
                                <tr>
                                    <td>Alamat :</td>
                                    <td class="text-right" id="alamat"></td>
                                </tr>
                                <tr>
                                    <td>Agama :</td>
                                    <td class="text-right" id="agama"></td>
                                </tr>
                                <tr>
                                    <td>Status Perkawinan :</td>
                                    <td class="text-right" id="status_perkawinan"></td>
                                </tr>
                                <tr>
                                    <td>Kewarganegaraan :</td>
                                    <td class="text-right" id="kewarganegaraan"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{{--  Jenis Surat Detail Modal end --}}


{{-- Delete Jenis Surat Modal start --}}

<div class="modal custom-modal fade" id="delete_jenis_surat" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalLongTitle">Hapus</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <h4 class="text-center">Anda yakin ingin hapus?</h4>
                <div class="modal-btn delete-action">
                    <div class="row">
                        <div class="col-6">
                            <form method="POST" id="url-delete">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-primary continue-btn w-100" type="submit">Hapus</button>
                            </form>
                        </div>
                        <div class="col-6">
                            <button type="button" data-dismiss="modal" class="btn btn-primary">Batal</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{{-- Delete Jenis Surat Modal end --}}

{{-- modal end --}}
@endsection

@push ('page-scripts')
<script>
    $(document).ready(function() {
        var table = $("#table-datatable").DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('jenis_surat.json') }}",
            columns: [
                {
                    data: "id",
                    name: "id",
                },
                {
                    data: "nama_surat",
                    name: "nama_surat",
                },
                {
                    data: "jenis_surat",
                    name: "jenis_surat"
                },
                {
                    data: "action",
                    name: "action",
                    className: 'text-center'
                },
            ],
            order: [[ 0, "desc" ]]
        });
        table.on('draw.dt', function () {
            var info = table.page.info();
            table.column(0, {
                search: 'applied', order: 'applied', page: 'applied'
            }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1 + info.start;
            });
        });

        // add jenis surat
        $('.add-btn').on('click', function(){            
            $('#modal_jenis_surat .modal-title span').html('Tambah');
            $('#modal_jenis_surat #id').val('');
            $('#modal_jenis_surat form').trigger('reset');


            var myModal = new bootstrap.Modal(document.getElementById('modal_jenis_surat'))
            myModal.show()
        });

        // edit jenis surat
        $("#table-datatable").on("click", ".btn-edit", function(e) {
            e.preventDefault();
            data = $(this).data();

            $.each(data, function(index, value){
                $('#modal_jenis_surat #'+index).val(value);
            })

            $('#modal_jenis_surat'+' .modal-title span').html('Edit');

            var myModal = new bootstrap.Modal(document.getElementById('modal_jenis_surat'))
            myModal.show()
        });

        // detail jenis surat
        $("#table-datatable").on("click", ".btn-detail", function(e) {
            e.preventDefault();
            data = $(this).data();
    
            $.each(data, function(index, value){
                $('#modal_jenis_surat_detail #'+index).html(value);
            })
    
            var myModal = new bootstrap.Modal(document.getElementById('modal_jenis_surat_detail'))
            myModal.show()
        });


        // delete jenis surat
        $("#table-datatable").on("click", ".btn-delete", function(e) {
            e.preventDefault();
            const id = $(this).data("id");
            $('#delete_jenis_surat #url-delete').attr('action', "{{ url('jenis_surat') }}/"+id);

    swal({
        title: 'Kamu Yakin Mau Hapus?',
        text: 'Jika di Hapus, Data akan hilang!',
        icon: 'warning',
        buttons: true,
        dangerMode: true,
      })
      .then((willDelete) => {
        if (willDelete) {
        swal('Data Berhasil diHapus :)', {
          icon: 'success',
        });
        $(`#url-delete`).submit();
        } else {
        swal('Data Kamu Aman!');
        }
      });
            // var myModal = new bootstrap.Modal(document.getElementById('delete_jenis_surat'))
            // myModal.show()
        });

    });
</script>
@endpush