routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PendudukController;
use App\Http\Controllers\DisposisiController;
use App\Http\Controllers\CetakSuratController;
use App\Http\Controllers\JenisSuratController;
use App\Http\Controllers\SuratMasukController;
use App\Http\Controllers\SuratKeluarController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {

    // Data Json 
Route::get('/penduduk/datajson', [PendudukController::class, 'dataJson'])->name('penduduk.json');
Route::get('/jenis_surat/datajson', [JenisSuratController::class, 'dataJson'])->name('jenis_surat.json');
Route::get('/surat_masuk/datajson', [SuratMasukController::class, 'dataJson'])->name('surat_masuk.json');
Route::get('/surat_keluar/datajson', [SuratKeluarController::class, 'dataJson'])->name('surat_keluar.json');
Route::get('/cetak/surat/datajson', [CetakSuratController::class, 'dataJson'])->name('cetak_surat.json');
Route::get('/disposisi/datajson', [DisposisiController::class, 'dataJson'])->name('disposisi.json');

Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
Route::get('/surat_masuk', [CetakSuratController::class, 'index'])->name('surat');
Route::post('/surat_masuk', [CetakSuratController::class, 'store'])->name('surat.store');
Route::delete('/surat_masuk/{id}', [CetakSuratController::class, 'destroy'])->name('surat.destroy');
Route::get('/cetak_surat', [CetakSuratController::class, 'index'])->name('cetak_surat');
Route::get('/disposisi', [DisposisiController::class, 'index'])->name('disposisi');
Route::get('/disposisi/acc/{id}', [DisposisiController::class, 'acc_disposisi'])->name('acc.disposisi');
Route::get('/surat_keluar/acc/{id}', [SuratKeluarController::class, 'acc_surat_keluar'])->name('acc.surat_keluar');
Route::get('/surat_keluar/tolak/{id}', [SuratKeluarController::class, 'tolak_surat_keluar'])->name('tolak.surat_keluar');

    // PDF
Route::get('/foto_surat_masuk/pdf/{id}', [CetakSuratController::class, 'foto_surat_masuk'])->name('foto_surat_masuk');
Route::get('/skck/pdf/{id}', [CetakSuratController::class, 'pdf_skck'])->name('pdf_skck');
Route::get('/pindah_rumah/pdf/{id}', [CetakSuratController::class, 'pdf_pindah_rumah'])->name('pdf_pindah');
Route::get('/blm_pny_rmh/pdf/{id}', [CetakSuratController::class, 'pdf_blm_pny_rmh'])->name('pdf_blm_pny');
Route::get('/nikah_satu/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_satu'])->name('pdf_nikah_satu');
Route::get('/nikah_empat/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_empat'])->name('pdf_nikah_empat');
Route::get('/nikah_lima/pdf/{id}', [CetakSuratController::class, 'pdf_nikah_lima'])->name('pdf_nikah_lima');
Route::get('/disposisi/pdf/{id}', [CetakSuratController::class, 'cetak_disposisi'])->name('pdf_disposisi');

Route::get('/report/surat_masuk', [CetakSuratController::class, 'surat_masuk'])->name('report.surat_masuk');
Route::get('/report/surat_Keluar', [CetakSuratController::class, 'surat_keluar'])->name('report.surat_keluar');
Route::get('/report/disposisi', [CetakSuratController::class, 'disposisi'])->name('report.disposisi');
Route::get('/cetak_report/surat_masuk', [CetakSuratController::class, 'report_surat_masuk'])->name('cetak_report.surat_masuk');

Route::get('/report/pdf_surat_masuk', [CetakSuratController::class, 'pdf_surat_masuk'])->name('report.pdf_surat_masuk');
Route::get('/report/pdf_surat_keluar', [CetakSuratController::class, 'pdf_surat_keluar'])->name('report.pdf_surat_keluar');
Route::get('/report/pdf_disposisi', [CetakSuratController::class, 'pdf_disposisi'])->name('report.pdf_disposisi');

Route::resource('penduduk', PendudukController::class);
Route::resource('jenis_surat', JenisSuratController::class);
Route::resource('surat_masuk', SuratMasukController::class);
Route::resource('surat_keluar', SuratKeluarController::class);
Route::resource('manajemen_user', UserController::class);

// Manajemen User
// Route::get('/manajemen_user', [UserController::class, 'index'])->name('manajemen_user.index');
// Route::post('/manajemen_user', [UserController::class, 'store'])->name('manajemen_user.store');
// Route::get('/manajemen_user/{manajemen_user}/edit', [UserController::class, 'edit'])->name('edit');
// Route::patch('/manajemen_user/update/{manajemen_user}', [UserController::class, 'update'])->name('update');
// Route::get('/manajemen_user/show/{manajemen_user}', [UserController::class, 'show'])->name('show');

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title>@yield('title') | Kelurahan Nusa Jaya</title>
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
	<link rel="icon" href="../assets/img/logo.png" type="image/x-icon"/>

	<!-- Fonts and icons -->
	<script src="../assets/js/plugin/webfont/webfont.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,700&display=swap" rel="stylesheet">

	<style>
		body,h1,.h1,h2,.h2,h3,.h3,h4,.h4,h5,.h5,h6,.h6,p,.navbar,.brand,.btn-simple,.alert,a,.td-name,td {font-family: 'Poppins' !important;}
	</style>
	<script>
		WebFont.load({
			// google: {"families":["Open+Sans:300,400,600,700"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands"], urls: ['../assets/css/fonts.css']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>

	<!-- CSS Files -->
	<link rel="stylesheet" href="../assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="../assets/css/azzara.min.css">
	<link rel="stylesheet" href="../assets/css/azzara.css">
	<link rel="stylesheet" href="../assets/css/jam.css">
	<link rel="stylesheet" href="https://demo.getstisla.com/assets/modules/jquery-selectric/selectric.css">
    <link rel="stylesheet" href="../assets/js/jquery-selectric/selectric.css">
	
	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link rel="stylesheet" href="../assets/css/demo.css">
</head>
    
    @stack('page-styles')

<body>
	<div class="wrapper">
		<!--
				Tip 1: You can change the background color of the main header using: data-background-color="blue | purple | light-blue | green | orange | red"
		-->
		<div class="main-header" data-background-color="coklat">
			<!-- Logo Header -->
			<div class="logo-header">

				<a href="/" class="logo ml-5">
					<img src="../assets/img/logo.png" alt="navbar brand" width="50" height="50" class="navbar-brand">
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="fa fa-bars"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="fa fa-ellipsis-v"></i></button>
				<div class="navbar-minimize">
					<button class="btn btn-minimize btn-rounded">
						<i class="fa fa-bars"></i>
					</button>
				</div>
			</div>
			<!-- End Logo Header -->

			<!-- Navbar Header -->
			@include('layouts.header')
			<!-- End Navbar -->
		</div>

		<!-- Sidebar -->
		@include('layouts.sidebar')
		<!-- End Sidebar -->

		<div class="main-panel">
			<div class="content">
				<div class="page-inner">
                    @yield('content')
				</div>
				@yield('modal')
			</div>
			<footer class="footer">
				<div class="container-fluid">
					{{-- <nav class="pull-left">
						<ul class="nav">
							<li class="nav-item">
								<a class="nav-link" href="http://www.themekita.com">
									ThemeKita
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									Help
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									Licenses
								</a>
							</li>
						</ul>
					</nav> --}}
					<div class="copyright ml-auto">
						made with <i class="fas fa-heart heart text-danger"></i>
					</div>
				</div>
			</footer>
		</div>
		<div class="quick-sidebar">
			<a href="#" class="close-quick-sidebar">
				<i class="flaticon-cross"></i>
			</a>
            <!-- Custom template | don't include it in your project! -->
		{{-- <div class="custom-template">
			<div class="title">Settings</div>
			<div class="custom-content">
				<div class="switcher">
					<div class="switch-block">
						<h4>Topbar</h4>
						<div class="btnSwitch">
							<button type="button" class="changeMainHeaderColor" data-color="blue"></button>
							<button type="button" class="selected changeMainHeaderColor" data-color="purple"></button>
							<button type="button" class="changeMainHeaderColor" data-color="light-blue"></button>
							<button type="button" class="changeMainHeaderColor" data-color="green"></button>
							<button type="button" class="changeMainHeaderColor" data-color="orange"></button>
							<button type="button" class="changeMainHeaderColor" data-color="red"></button>
							<button type="button" class="changeMainHeaderColor" data-color="dark"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Background</h4>
						<div class="btnSwitch">
							<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
							<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
							<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
							<button type="button" class="changeBackgroundColor" data-color="bg4"></button>
						</div>
					</div>
				</div>
			</div>
			<div class="custom-toggle">
				<i class="flaticon-settings"></i>
			</div>
		</div> --}}
		<!-- End Custom template -->
		</div>
	</div>
	@include('sweetalert::alert')

    @stack('before-scripts')
	<!--   Core JS Files   -->
	<script src="../assets/js/core/jquery.3.2.1.min.js"></script>
	<script src="../assets/js/core/popper.min.js"></script>
	<script src="../assets/js/core/bootstrap.min.js"></script>

	<!-- jQuery UI -->
	<script src="../assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
	<script src="../assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>

	<!-- jQuery Scrollbar -->
	<script src="../assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

	<!-- Moment JS -->
	<script src="../assets/js/plugin/moment/moment.min.js"></script>

	<!-- Chart JS -->
	<script src="../assets/js/plugin/chart.js/chart.min.js"></script>

	<!-- jQuery Sparkline -->
	<script src="../assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

	<!-- Chart Circle -->
	<script src="../assets/js/plugin/chart-circle/circles.min.js"></script>

	<!-- Datatables -->
	<script src="../assets/js/plugin/datatables/datatables.min.js"></script>

	<!-- Bootstrap Notify -->
	<script src="../assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

	<!-- Bootstrap Toggle -->
	<script src="../assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>


	<!-- Dropzone -->
	<script src="../assets/js/plugin/dropzone/dropzone.min.js"></script>


	<!-- DateTimePicker -->
	<script src="../assets/js/plugin/datepicker/bootstrap-datetimepicker.min.js"></script>

	<!-- Bootstrap Tagsinput -->
	<script src="../assets/js/plugin/bootstrap-tagsinput/bootstrap-tagsinput.min.js"></script>


	<!-- jQuery Validation -->
	<script src="../assets/js/plugin/jquery.validate/jquery.validate.min.js"></script>

	<!-- Select2 -->
	<script src="../assets/js/plugin/select2/select2.full.min.js"></script>

	<!-- Sweet Alert -->
	<script src="../assets/js/plugin/sweetalert/sweetalert.min.js"></script>
    <script src="../assets/js/jquery-selectric/jquery.selectric.min.js"></script>

    @stack('page-scripts')

	<!-- Azzara JS -->
	<script src="../assets/js/ready.min.js"></script>
	<script src="../assets/js/jam.js"></script>
	<script src="../assets/js/setting-demo.js"></script>
</body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-header navbar-expand-lg">

    <div class="container-fluid">
	<h5 class="page-title mt-3 text-white">Kelurahan Nusa Jaya</h5>
        <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
            <li class="nav-item toggle-nav-search hidden-caret">
                <a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
                    <i class="fa fa-search"></i>
                </a>
            </li>
            {{-- <li class="nav-item dropdown hidden-caret">
                <a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-bell"></i>
                    <span class="notification">4</span>
                </a>
                <ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
                    <li>
                        <div class="dropdown-title">You have 4 new notification</div>
                    </li>
                    <li>
                        <div class="notif-center">
                            <a href="#">
                                <div class="notif-icon notif-primary"> <i class="fa fa-user-plus"></i> </div>
                                <div class="notif-content">
                                    <span class="block">
                                        New user registered
                                    </span>
                                    <span class="time">5 minutes ago</span>
                                </div>
                            </a>
                            <a href="#">
                                <div class="notif-icon notif-success"> <i class="fa fa-comment"></i> </div>
                                <div class="notif-content">
                                    <span class="block">
                                        Rahmad commented on Admin
                                    </span>
                                    <span class="time">12 minutes ago</span>
                                </div>
                            </a>
                            <a href="#">
                                <div class="notif-img">
                                    <img src="../assets/img/profile2.jpg" alt="Img Profile">
                                </div>
                                <div class="notif-content">
                                    <span class="block">
                                        Reza send messages to you
                                    </span>
                                    <span class="time">12 minutes ago</span>
                                </div>
                            </a>
                            <a href="#">
                                <div class="notif-icon notif-danger"> <i class="fa fa-heart"></i> </div>
                                <div class="notif-content">
                                    <span class="block">
                                        Farrah liked Admin
                                    </span>
                                    <span class="time">17 minutes ago</span>
                                </div>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="see-all" href="javascript:void(0);">See all notifications<i class="fa fa-angle-right"></i> </a>
                    </li>
                </ul>
            </li> --}}
            <li class="nav-item dropdown hidden-caret">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                    <div class="avatar-sm">
                        <img src="../assets/img/profile.png" alt="..." class="avatar-img rounded-circle">
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-user animated fadeIn">
                    <li>
                        {{-- <div class="dropdown-divider"></div> --}}
                        {{-- <a class="dropdown-item" href="#">My Profile</a>
                        <a class="dropdown-item" href="#">My Balance</a>
                        <a class="dropdown-item" href="#">Inbox</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Account Setting</a> --}}
                        {{-- <div class="dropdown-divider"></div> --}}
                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="dropdown-item has-icon text-danger">Logout
                            <i class="fas fa-sign-out-alt"></i></a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                              @csrf
                          </form>
                        {{-- <a class="dropdown-item" href="#">Logout</a> --}}
                    </li>
                </ul>
            </li>
            {{-- <li class="nav-item">
                <a href="#" class="nav-link quick-sidebar-toggler">
                    <i class="fa fa-th"></i>
                </a>
            </li> --}}
        </ul>
    </div>
</nav>

resources/views/layouts/sidebar.blade.php
<div class="sidebar">

    {{-- <div class="sidebar-background"></div> --}}
    <div class="sidebar-wrapper scrollbar-inner">
        <div class="sidebar-content">
            {{-- <div class="user">
                <div class="avatar-sm float-left mr-2">
                    <img src="../assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle">
                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                        <span>
                            Hizrian
                            <span class="user-level">Administrator</span>
                            <span class="caret"></span>
                        </span>
                    </a>
                    <div class="clearfix"></div>

                    <div class="collapse in" id="collapseExample">
                        <ul class="nav">
                            <li>
                                <a href="#profile">
                                    <span class="link-collapse">My Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="#edit">
                                    <span class="link-collapse">Edit Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="#settings">
                                    <span class="link-collapse">Settings</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div> --}}
            <ul class="nav">
                <li class="nav-item {{ Request::is('dashboard') ? 'active' : '' }}">
                    <a href="/">
                        <i class="flaticon-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                @if (Auth::user()->role == 'staff')
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Menu</h4>
                </li>

                <li class="nav-item {{ Request::is('manajemen_user', 'penduduk','jenis_surat') ? 'active submenu' : '' }}">
                    <a data-toggle="collapse" href="#base">
                        <i class="flaticon-layers"></i>
                        <p>Data Master</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse {{ Request::is('manajemen_user','penduduk','jenis_surat') ? 'show' : '' }}" id="base">
                        <ul class="nav nav-collapse">
                            <li class=" {{ Request::is('manajemen_user') ? 'active' : '' }}">
                                <a href="{{ route('manajemen_user.index') }}">
                                    <span class="sub-item">Data User</span>
                                </a>
                            </li>
                            <li class="{{ Request::is('penduduk') ? 'active' : '' }}">
                                <a href="{{ route('penduduk.index') }}">
                                    <span class="sub-item">Data Penduduk</span>
                                </a>
                            </li>
                            {{-- <li class="{{ Request::is('jenis_surat') ? 'active' : '' }}">
                                <a href="{{ route('jenis_surat.index') }}">
                                    <span class="sub-item">Jenis Surat</span>
                                </a>
                            </li> --}}
                        </ul>
                    </div>
                </li>
                @endif
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Surat</h4>
                </li>
                @if (Auth::user()->role == 'staff')
                <li class="nav-item {{ Request::is('surat_masuk', 'surat_keluar') ? 'active submenu' : '' }}">
                    <a data-toggle="collapse" href="#surat">
                        <i class="flaticon-layers"></i>
                        <p>Data Surat</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse {{ Request::is('surat_masuk', 'surat_keluar') ? 'show' : '' }}" id="surat">
                        <ul class="nav nav-collapse">
                            <li class=" {{ Request::is('surat_masuk') ? 'active' : '' }}">
                                <a href="{{ route('surat_masuk.index') }}">
                                    <span class="sub-item">Surat Masuk</span>
                                </a>
                            </li>
                            <li class="{{ Request::is('surat_keluar') ? 'active' : '' }}">
                                <a href="{{ route('surat_keluar.index') }}">
                                    <span class="sub-item">Surat Keluar</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                @endif
                <li class="nav-item {{ Request::is('disposisi') ? 'active' : '' }}">
                    <a href="{{ route('disposisi') }}">
                        <i class="fas fa-file-archive"></i>
                        <p>Disposisi</p>
                    </a>
                </li>
                @if (Auth::user()->role == 'staff')
                <li class="nav-item {{ Request::is('cetak_surat') ? 'active' : '' }}">
                    <a href="{{ route('cetak_surat') }}">
                        <i class="flaticon-calendar"></i>
                        <p>Cetak Surat</p>
                    </a>
                </li>
                @endif
                <li class="nav-item {{ Request::is('laporan_surat_masuk', 'report/surat_keluar', 'report/disposisi') ? 'active submenu' : '' }}">
                    <a data-toggle="collapse" href="#laporan">
                        <i class="flaticon-layers"></i>
                        <p>Laporan</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse {{ Request::is('report/surat_masuk', 'report/surat_keluar', 'report/disposisi') ? 'show' : '' }}" id="laporan">
                        <ul class="nav nav-collapse">
                            <li class=" {{ Request::is('report/surat_masuk') ? 'active' : '' }}">
                                <a href="{{ route('report.surat_masuk') }}">
                                    <span class="sub-item">Laporan Surat Masuk</span>
                                </a>
                            </li>
                            <li class="{{ Request::is('report/surat_keluar') ? 'active' : '' }}">
                                <a href="{{ route('report.surat_keluar') }}">
                                    <span class="sub-item">Laporan Surat Keluar</span>
                                </a>
                            </li>
                            <li class="{{ Request::is('report/disposisi') ? 'active' : '' }}">
                                <a href="{{ route('report.disposisi') }}">
                                    <span class="sub-item">Laporan Disposisi</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>